---
name: CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: |-
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        make lint test
