---
name: publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GCR Registry
        run: echo ${{ secrets.GCR_TOKEN }} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io/${{ github.repository }}

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA})

      - name: pull latest for caching
        run: docker pull ghcr.io/${{ github.repository }}:latest

      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:${{steps.vars.outputs.tag}}

      - name: push latest tag
        if: github.ref == 'refs/heads/master'
        run: |-
          docker tag ghcr.io/${{ github.repository }}:${{steps.vars.outputs.tag}} ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{steps.vars.outputs.tag}}
          docker push ghcr.io/${{ github.repository }}:latest
